// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIL202PldPnt_IjP3WPhdraCQZvI-bjUk',
    appId: '1:939522286618:web:0b912c19c51c535bdedda3',
    messagingSenderId: '939522286618',
    projectId: 'fir-tutorial-ce545',
    authDomain: 'fir-tutorial-ce545.firebaseapp.com',
    storageBucket: 'fir-tutorial-ce545.appspot.com',
    measurementId: 'G-9LRYK9241N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHxbQqPhxtLY73kH-DZpS2yQEB0MdXtqQ',
    appId: '1:939522286618:android:e35cfe5ea4dbf180dedda3',
    messagingSenderId: '939522286618',
    projectId: 'fir-tutorial-ce545',
    storageBucket: 'fir-tutorial-ce545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxz2LKCMaSA-DvRNqFu-TsPZLy2RpS2tc',
    appId: '1:939522286618:ios:18a5bc05214f9cdddedda3',
    messagingSenderId: '939522286618',
    projectId: 'fir-tutorial-ce545',
    storageBucket: 'fir-tutorial-ce545.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
